// Generated by CoffeeScript 1.10.0

/*
 */

(function() {
  var UserModel, UserView, userView;

  UserModel = Backbone.Model.extend({
    url: '/api/registration',
    defaults: {
      name: '',
      password: '',
      confirm: '',
      validate: function(attrs, options) {
        if (attrs.end < attrs.start) {
          return console.log("can't end before it starts");
        }
      }
    }
  });


  /*
   */

  UserView = Backbone.View.extend({
    el: $('#registration'),
    model: UserModel,
    initialize: function() {
      _.bindAll(this, 'onFormSubmit');
      return this.model.bind('change:name', this.changeTitle);
    },
    onFormSubmit: function(e) {
      var formData, frm, i, j, len, ref;
      console.log('submit', this, '--', e, '--el:', this.el);
      formData = [];
      ref = this.el;
      for (i = j = 0, len = ref.length; j < len; i = ++j) {
        frm = ref[i];
        if (frm.type !== 'submit') {
          formData[frm.name] = frm.value;
        }
      }
      console.log('model:', this.model);
      console.log('formData:', formData);
      return false;
    },
    changeTitle: function(e) {
      console.log('submit', this, '--', e);
      return false;
    },
    events: {
      'submit': 'onFormSubmit'
    }
  });

  userView = new UserView;

}).call(this);
